services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: mychoice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mychoice
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file: .env
    environment:
      VITE_API_URL: http://backend:8000
    # volumes:
    #   - ./frontend:/web
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
